name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the repository! Thank you for creating an issue. We'll get back to you as soon as possible."
        pr-message: "Hello! Thanks for opening a pull request. We appreciate your contribution. Our team will review it shortly."